### ISSUE TITLE
Фильтр по шрифтам на ониксе

### ISSUE THREAD

**Issue by plotn** [plotn/coolreader#543]
То ли не работает, то ли я не пойму... но с фильтрацией вот:

2021-11-25 18:56:41.836 976-976/org.knownreader.premium E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.knownreader.premium, PID: 976
    java.lang.IndexOutOfBoundsException: Invalid index 52, size is 8
        at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
        at java.util.ArrayList.get(ArrayList.java:308)
        at org.coolreader.crengine.OptionsDialog$ListOption.lambda$onSelect$5$org-coolreader-crengine-OptionsDialog$ListOption(OptionsDialog.java:5648)
        at org.coolreader.crengine.OptionsDialog$ListOption$$ExternalSyntheticLambda6.onItemClick(Unknown Source)
        at android.widget.AdapterView.performItemClick(AdapterView.java:299)
        at android.widget.AbsListView.performItemClick(AbsListView.java:1113)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:2911)
        at android.widget.AbsListView$3.run(AbsListView.java:3646)
        at android.os.Handler.handleCallback(Handler.java:733)

**Comment by plotn** [comment]
На телефоне тоже возникает
