### ISSUE TITLE
Какой то баг

### ISSUE THREAD

**Issue by plotn** [plotn/coolreader#700]
04-23 12:17:22.474 31859 31878 D cr3     : B|rvrs| doDraw() called
04-23 12:17:22.475 31859 31878 D cr3     : B|rvrs| onDraw() -- drawing progress 0
04-23 12:17:22.475 31859 31878 E cr3     : B|rvrs| exception while drawing
04-23 12:17:22.475 31859 31878 E cr3     : android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
04-23 12:17:22.475 31859 31878 E cr3     : 	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:8031)
04-23 12:17:22.475 31859 31878 E cr3     : 	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1276)
04-23 12:17:22.475 31859 31878 E cr3     : 	at android.view.View.requestLayout(View.java:23120)
04-23 12:17:22.475 31859 31878 E cr3     : 	at android.view.View.setLayoutParams(View.java:16116)
04-23 12:17:22.475 31859 31878 E cr3     : 	at android.view.WindowManagerGlobal.updateViewLayout(WindowManagerGlobal.java:421)
04-23 12:17:22.475 31859 31878 E cr3     : 	at android.view.WindowManagerImpl.updateViewLayout(WindowManagerImpl.java:101)
04-23 12:17:22.475 31859 31878 E cr3     : 	at android.app.Activity.onWindowAttributesChanged(Activity.java:3291)
04-23 12:17:22.475 31859 31878 E cr3     : 	at android.view.Window.setExtraFlags(Window.java:2399)
04-23 12:17:22.475 31859 31878 E cr3     : 	at android.view.Window.clearExtraFlags(Window.java:2387)
04-23 12:17:22.475 31859 31878 E cr3     : 	at com.android.internal.policy.PhoneWindowInjector.onNavigationBarColorChange(PhoneWindowInjector.java:18)
04-23 12:17:22.475 31859 31878 E cr3     : 	at com.android.internal.policy.PhoneWindow.setNavigationBarColor(PhoneWindow.java:3827)
04-23 12:17:22.475 31859 31878 E cr3     : 	at org.coolreader.readerview.ReaderView.drawPageBackground(ReaderView.java:5346)
04-23 12:17:22.475 31859 31878 E cr3     : 	at org.coolreader.readerview.ReaderView.drawPageBackground(ReaderView.java:5429)
04-23 12:17:22.475 31859 31878 E cr3     : 	at org.coolreader.readerview.ReaderSurface.doDraw(ReaderSurface.java:108)
04-23 12:17:22.475 31859 31878 E cr3     : 	at org.coolreader.readerview.ReaderSurface$$ExternalSyntheticLambda1.drawTo(Unknown Source:2)
04-23 12:17:22.475 31859 31878 E cr3     : 	at org.coolreader.readerview.ReaderView.drawCallback(ReaderView.java:4950)
04-23 12:17:22.475 31859 31878 E cr3     : 	at org.coolreader.readerview.ReaderSurface.draw(ReaderSurface.java:241)
04-23 12:17:22.475 31859 31878 E cr3     : 	at org.coolreader.readerview.DrawPageTask.work(DrawPageTask.java:49)
04-23 12:17:22.475 31859 31878 E cr3     : 	at org.coolreader.crengine.Engine$TaskHandler.run(Engine.java:236)
04-23 12:17:22.475 31859 31878 E cr3     : 	at android.os.Handler.handleCallback(Handler.java:873)
04-23 12:17:22.475 31859 31878 E cr3     : 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-23 12:17:22.475 31859 31878 E cr3     : 	at android.os.Looper.loop(Looper.java:207)
04-23 12:17:22.475 31859 31878 E cr3     : 	at org.coolreader.crengine.BackgroundThread.run(BackgroundThread.java:122)
04-23 12:17:22.529 31859 31859 V cr3     : G|rv| synced posting LoadDocument task to GUI thread

**Comment by plotn** [comment]
04-23 10:09:38.321 28764 28782 V cr3eng  : getPageImageInternal entered : bpp=32
04-23 10:09:38.322 28764 28782 D cr3     : B|rvrs| doDraw() called
04-23 10:09:38.322 28764 28782 D cr3     : B|rvrs| onDraw() -- drawing progress 0
04-23 10:09:38.323 28764 28782 E cr3     : B|rvrs| exception while drawing
04-23 10:09:38.323 28764 28782 E cr3     : android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
04-23 10:09:38.323 28764 28782 E cr3     : 	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:8031)
04-23 10:09:38.323 28764 28782 E cr3     : 	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1276)
04-23 10:09:38.323 28764 28782 E cr3     : 	at android.view.View.requestLayout(View.java:23120)
04-23 10:09:38.323 28764 28782 E cr3     : 	at android.view.View.setLayoutParams(View.java:16116)
04-23 10:09:38.323 28764 28782 E cr3     : 	at android.view.WindowManagerGlobal.updateViewLayout(WindowManagerGlobal.java:421)
04-23 10:09:38.323 28764 28782 E cr3     : 	at android.view.WindowManagerImpl.updateViewLayout(WindowManagerImpl.java:101)
04-23 10:09:38.323 28764 28782 E cr3     : 	at android.app.Activity.onWindowAttributesChanged(Activity.java:3291)
04-23 10:09:38.323 28764 28782 E cr3     : 	at android.view.Window.setExtraFlags(Window.java:2399)
04-23 10:09:38.323 28764 28782 E cr3     : 	at android.view.Window.clearExtraFlags(Window.java:2387)
04-23 10:09:38.323 28764 28782 E cr3     : 	at com.android.internal.policy.PhoneWindowInjector.onNavigationBarColorChange(PhoneWindowInjector.java:18)
04-23 10:09:38.323 28764 28782 E cr3     : 	at com.android.internal.policy.PhoneWindow.setNavigationBarColor(PhoneWindow.java:3827)
04-23 10:09:38.323 28764 28782 E cr3     : 	at org.coolreader.readerview.ReaderView.drawPageBackground(ReaderView.java:5345)
04-23 10:09:38.323 28764 28782 E cr3     : 	at org.coolreader.readerview.ReaderView.drawPageBackground(ReaderView.java:5428)
04-23 10:09:38.323 28764 28782 E cr3     : 	at org.coolreader.readerview.ReaderSurface.doDraw(ReaderSurface.java:108)
04-23 10:09:38.323 28764 28782 E cr3     : 	at org.coolreader.readerview.ReaderSurface$$ExternalSyntheticLambda1.drawTo(Unknown Source:2)
04-23 10:09:38.323 28764 28782 E cr3     : 	at org.coolreader.readerview.ReaderView.drawCallback(ReaderView.java:4949)
04-23 10:09:38.323 28764 28782 E cr3     : 	at org.coolreader.readerview.ReaderSurface.draw(ReaderSurface.java:241)
04-23 10:09:38.323 28764 28782 E cr3     : 	at org.coolreader.readerview.DrawPageTask.work(DrawPageTask.java:49)
04-23 10:09:38.323 28764 28782 E cr3     : 	at org.coolreader.crengine.Engine$TaskHandler.run(Engine.java:236)
04-23 10:09:38.323 28764 28782 E cr3     : 	at android.os.Handler.handleCallback(Handler.java:873)
04-23 10:09:38.323 28764 28782 E cr3     : 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-23 10:09:38.323 28764 28782 E cr3     : 	at android.os.Looper.loop(Looper.java:207)
04-23 10:09:38.323 28764 28782 E cr3     : 	at org.coolreader.crengine.BackgroundThread.run(BackgroundThread.java:122)
04-23 10:09:38.348 28764 28764 V cr3     : G|rv| synced posting LoadDocument task to GUI thread

**Comment by plotn** [comment]
вроде исправил, будем смотреть.
