### ISSUE TITLE
Еще интересный баг

### ISSUE THREAD

**Issue by plotn** [plotn/coolreader#702]
--------- beginning of crash
04-24 00:57:48.850 10834 10834 E AndroidRuntime: FATAL EXCEPTION: main
04-24 00:57:48.850 10834 10834 E AndroidRuntime: Process: org.knownreader.premium, PID: 10834
04-24 00:57:48.850 10834 10834 E AndroidRuntime: java.lang.NullPointerException: Attempt to write to field 'org.coolreader.crengine.BookInfo org.coolreader.crengine.PictureReceived.book' on a null object reference in method 'void org.coolreader.crengine.PictureCameDialog.<init>(org.coolreader.crengine.BaseActivity, java.lang.Object, java.lang.String, java.lang.String)'
04-24 00:57:48.850 10834 10834 E AndroidRuntime: 	at org.coolreader.crengine.PictureCameDialog.<init>(PictureCameDialog.java:267)
04-24 00:57:48.850 10834 10834 E AndroidRuntime: 	at org.coolreader.crengine.FileBrowser.onContextItemSelected(FileBrowser.java:896)
04-24 00:57:48.850 10834 10834 E AndroidRuntime: 	at org.coolreader.crengine.FileBrowser$FileBrowserListView.lambda$createContextMenu$2$org-coolreader-crengine-FileBrowser$FileBrowserListView(FileBrowser.java:313)
04-24 00:57:48.850 10834 10834 E AndroidRuntime: 	at org.coolreader.crengine.FileBrowser$FileBrowserListView$$ExternalSyntheticLambda1.onMenuItemClick(Unknown Source:2)
04-24 00:57:48.850 10834 10834 E AndroidRuntime: 	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:148)
04-24 00:57:48.850 10834 10834 E AndroidRuntime: 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:935)
04-24 00:57:48.850 10834 10834 E AndroidRuntime: 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:925)
04-24 00:57:48.850 10834 10834 E AndroidRuntime: 	at com.android.internal.view.menu.MenuDialogHelper.onClick(MenuDialogHelper.java:170)
04-24 00:57:48.850 10834 10834 E AndroidRuntime: 	at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1258)
04-24 00:57:48.850 10834 10834 E AndroidRuntime: 	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
04-24 00:57:48.850 10834 10834 E AndroidRuntime: 	at android.widget.AbsListView.performItemClick(AbsListView.java:1199)
04-24 00:57:48.850 10834 10834 E AndroidRuntime: 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3213)
04-24 00:57:48.850 10834 10834 E AndroidRuntime: 	at android.widget.AbsListView$3.run(AbsListView.java:4179)
04-24 00:57:48.850 10834 10834 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
04-24 00:57:48.850 10834 10834 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-24 00:57:48.850 10834 10834 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:210)
04-24 00:57:48.850 10834 10834 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:299)
04-24 00:57:48.850 10834 10834 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8136)
04-24 00:57:48.850 10834 10834 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-24 00:57:48.850 10834 10834 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
04-24 00:57:48.850 10834 10834 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)

**Comment by plotn** [comment]
вроде вылечил, проверим
