### ISSUE TITLE
Firefox -> cr eink

### ISSUE THREAD

**Issue by plotn** [plotn/coolreader#82]
падает...

**Comment by plotn** [comment]
https://stackoverflow.com/questions/35337342/android-setbackgroundresource-acting-different-in-api-16-19
button_bg_dashed_border - troble

**Comment by plotn** [comment]
E/AndroidRuntime( 2376): FATAL EXCEPTION: BackgroundThread41986e90
E/AndroidRuntime( 2376): Process: org.coolreader.mod.plotn, PID: 2376
E/AndroidRuntime( 2376): android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
E/AndroidRuntime( 2376): 	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6204)
E/AndroidRuntime( 2376): 	at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:882)
E/AndroidRuntime( 2376): 	at android.view.ViewGroup.invalidateChild(ViewGroup.java:4325)
E/AndroidRuntime( 2376): 	at android.view.View.invalidate(View.java:10996)
E/AndroidRuntime( 2376): 	at android.view.View.invalidate(View.java:10961)
E/AndroidRuntime( 2376): 	at android.view.View.setEnabled(View.java:6112)
E/AndroidRuntime( 2376): 	at android.widget.TextView.setEnabled(TextView.java:1397)
E/AndroidRuntime( 2376): 	at org.coolreader.crengine.ExternalDocCameDialog$3$3.run(ExternalDocCameDialog.java:181)
E/AndroidRuntime( 2376): 	at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime( 2376): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 2376): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 2376): 	at org.coolreader.crengine.BackgroundThread.run(BackgroundThread.java:122)
W/ActivityManager(  349):   Force finishing activity org.coolreader.mod.plotn/org.coolreader.CoolReader
